# Generated by Django 2.0.6 on 2018-06-28 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorldCupTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('group', models.CharField(max_length=20)),
                ('firsrgame_time', models.DateTimeField()),
                ('firstgame_score', models.IntegerField(default=0)),
                ('secondgame_time', models.DateTimeField()),
                ('secondgame_score', models.IntegerField(default=0)),
                ('thirdgame_time', models.DateTimeField()),
                ('thirdgame_score', models.IntegerField(default=0)),
            ],
        ),
    ]
