# Generated by Django 2.0.6 on 2018-06-29 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myworldcup', '0002_auto_20180628_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldcupteam',
            name='firstgame_competitor',
            field=models.CharField(default='A1', max_length=20),
        ),
        migrations.AddField(
            model_name='worldcupteam',
            name='secondgame_competitor',
            field=models.CharField(default='A1', max_length=20),
        ),
    ]
