# Generated by Django 2.0.6 on 2018-06-29 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myworldcup', '0004_worldcupteam_thirdgame_competitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worldcupteam',
            name='firstgame_competitor',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='worldcupteam',
            name='secondgame_competitor',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='worldcupteam',
            name='thirdgame_competitor',
            field=models.IntegerField(default=0),
        ),
    ]
